### ISSUE TITLE
Selected event?

### ISSUE THREAD

**Issue by grvhi** [jakiestfu/Mention.js#14]
Is there an option to have a callback after selecting a mention item from the list? Twitter Typeahead (not the bootstrap version) has a `selected` event, but Mention.js doesn't seem to work with Typeahead....?

Thanks!

**Comment by jakiestfu** [comment]
@Erve1879 Sorry for the late response. The Typeahead library used is `bootstrap-typeahead.js`, not the new version. I've updated the repo to include `bootstrap-typeahead.js`

**Comment by grvhi** [comment]
@jakiestfu - not late at all. Thanks - will try try it again tomorrow.

**Comment by grvhi** [comment]
@jakiestfu - Sorry, I obviously missed your point. You're saying that there is no selected event or complete callback of some kind? Or any way in which I can trigger a function after a username is selected?

**Comment by matthewborgcarr** [comment]
How to add a callback to return the selected object?

Mat

**Comment by TiagoSilvaPereira** [comment]
Is there any way to do it?

**Comment by aleaforny** [comment]
updatOn my hand, I managed to make it work, with the `updater` function parameter within the `typeaheadOpts` options.

```
typeaheadOpts: {
    items: 5,
    updater: function(item) {
        // Do anything with "item" here. It's the value of the input.

        // Below is the function from source code _updater (required to work)
        var data = this.query,
        caratPos = this.$element[0].selectionStart, i;
    
        for (i = caratPos; i >= 0; i--) {
            if (data[i] === "@") {
                break;
            }
        }
        var replace = data.substring(i, caratPos),
            textBefore = data.substring(0, i),
            textAfter = data.substring(caratPos),
            data = textBefore + "@" + item + textAfter;
    
        this.tempQuery = data;

        // Don't forget to return the item (as per the initial function does)
        return item;
    }
}
```

Hope it helps.
