### ISSUE TITLE
Error when you type the same user twice in the same text field

### ISSUE THREAD

**Issue by tomasherrera** [jakiestfu/Mention.js#3]
When you type in the same username in the same text field it does something weird: for example: When I want to type this: "@tomaszed91 but this plugin has a bug @tomaszed91", when I going to type the second time and I press enter it ends up like this: "@tomaszed91aszed91 but this plugin has a bug @tom", Im using bootstrap on Rails 3.2, thanks

**Comment by jakiestfu** [comment]
Word, thanks for this bug. I'll get to this later today

**Comment by tomasherrera** [comment]
Did you find the issue?

**Comment by jakiestfu** [comment]
Fixed: 0104907ee52e8789a32b868a324a912b2432553a

**Comment by tomasherrera** [comment]
THANKS YOU ARE PRO!

**Comment by jakiestfu** [comment]
Hahaha you got it man! Thank you!
