### ISSUE TITLE
Possible to use this on elements aside from textareas? (wysiwyg)

### ISSUE THREAD

**Issue by dep-deprecated** [jakiestfu/Mention.js#47]
I'm having trouble getting this to work with my Wysiwyg editor, which renders as an editable <div> instead of a textarea.  Is it possible to extend this lib to work nicely with elements outside of textareas?

**Comment by robsilva** [comment]
I am having the same issue with summernote.js

**Comment by WisdomSky** [comment]
I think it is possible but since not all wysiwyg editors are the same speaking of structure and how and where they store the values, we may be able to add support for a certain wysiwyg editor but can't guarantee to work on other wysiwyg editors.
